<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Browse_Product</name>
   <tag></tag>
   <elementGuidId>e198df0c-2c35-4736-9dd6-3ab891a8dfd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='keyword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;keyword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ac1a596-9a36-41c0-a1e3-c0ec940d10b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ecb37dfa-46e1-4a42-b581-63251f509f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyword</value>
      <webElementGuid>557568e5-503b-4501-8fc2-50ba54bcb34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9d461749-3b9b-418d-8d59-0a1d1b1224ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari baju, toko, brand</value>
      <webElementGuid>0efa8fa9-31da-47d9-a34d-f92e0835e7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/header[1]/div[@class=&quot;header-container&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main-wrapper&quot;]/div[@class=&quot;header-community&quot;]/div[@class=&quot;header-search&quot;]/form[1]/input[1]</value>
      <webElementGuid>31c7fa68-8253-4d80-a2d8-e5d0748b739c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='keyword']</value>
      <webElementGuid>ed38f244-1ec0-42dc-9f54-76b89f8dce45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/header/div/div[2]/div/div[3]/div/form/input</value>
      <webElementGuid>24bfa416-6cd3-4e1a-ae3e-38e262111b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>955dcc70-323a-4459-9f62-c9ec59c12235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'keyword' and @placeholder = 'Cari baju, toko, brand']</value>
      <webElementGuid>be47b996-67f6-4987-a34e-453faecb1e43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
