<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image_Map_Club</name>
   <tag></tag>
   <elementGuidId>32588800-a519-45a6-8f28-02683ca5486d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/header/div/div[2]/div/div/section/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7baa12b0-6b10-44a8-8297-80570034f57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.mapclub.com/resources/v2/images/common/mapclub-logo.svg</value>
      <webElementGuid>80d59f55-19fa-4b6a-9333-95c5bdde70eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MAPCLUB</value>
      <webElementGuid>f6f37ead-3a1b-46a4-90d6-62e0e9a2aa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>95</value>
      <webElementGuid>6efefb22-ab51-4a23-b329-2d77316794dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>89f0a57b-c82d-464d-9c1d-fef142f32574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-logo</value>
      <webElementGuid>a26fc2f8-d857-4d39-88d4-8130133c3658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/header[1]/div[@class=&quot;header-container&quot;]/div[@class=&quot;header-main&quot;]/div[@class=&quot;header-main-wrapper&quot;]/div[@class=&quot;header__icons&quot;]/section[@class=&quot;header-main-logo&quot;]/a[1]/img[@class=&quot;img-logo&quot;]</value>
      <webElementGuid>9c7d60c1-ee54-47ee-9b36-7c167bc22ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/header/div/div[2]/div/div/section/a/img</value>
      <webElementGuid>7307fb13-3e33-4594-a2fc-220112f75ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MAPCLUB']</value>
      <webElementGuid>42b1ce43-a18c-4f19-8bb1-272cc3112013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>70ef346d-00e4-43fc-82bc-208a49ff16e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.mapclub.com/resources/v2/images/common/mapclub-logo.svg' and @alt = 'MAPCLUB']</value>
      <webElementGuid>805da537-2c36-40f8-bf9a-07e362784609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
