<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Image_Jago_fon</name>
   <tag></tag>
   <elementGuidId>948bc6eb-c137-42b0-9c04-27dcd2df0a75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/header/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.header-logo__image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e24956f-eed9-45e4-9900-6785394d451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_ipx/_/images/logo-green.svg</value>
      <webElementGuid>d81fd397-095f-4395-9c1e-5ef9acfb05af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Jagofon logo</value>
      <webElementGuid>b26d9b4b-b08a-4031-920f-4c68bbccd5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-logo__image</value>
      <webElementGuid>2f6343f6-9f43-4b95-97da-4e38c3461bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/header[@class=&quot;header&quot;]/a[@class=&quot;header-logo nuxt-link-exact-active nuxt-link-active&quot;]/img[@class=&quot;header-logo__image&quot;]</value>
      <webElementGuid>0c9adbf1-c312-40cf-b757-1ecf7ecad981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/header/a/img</value>
      <webElementGuid>2f10820c-97f6-4327-842c-7bd37a0feabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Jagofon logo']</value>
      <webElementGuid>456caac6-2e29-4259-acf0-83e5031aaccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>79617922-6f62-4bcc-b245-4e20bf9fd5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_ipx/_/images/logo-green.svg' and @alt = 'Jagofon logo']</value>
      <webElementGuid>00d81270-4c3a-47f7-8578-ac7878fab9ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
